import type { UserTier } from "../../contracts/v3_types";
import type { TenantSurveillanceRow, AdminPoolHealthResponse } from "./types";

// In-memory state storage for surveillance and overrides
const initialTenants: TenantSurveillanceRow[] = [
  {
    tenantId: "tenant_probationary_01",
    email: "dev1@example.com",
    authProvider: "email",
    tier: "probationary",
    currentRpm: 1,
    rpmLimit: 2,
    todaySpendMicrodollars: 15000,
    activeKeyCount: 1,
    isQuarantined: false,
    lastActiveTimestamp: Date.now() - 120000,
  },
  {
    tenantId: "tenant_builder_02",
    email: "builder@example.com",
    authProvider: "github",
    tier: "builder",
    currentRpm: 12,
    rpmLimit: 20,
    todaySpendMicrodollars: 240000,
    activeKeyCount: 4,
    isQuarantined: false,
    lastActiveTimestamp: Date.now() - 30000,
  },
  {
    tenantId: "tenant_quarantined_03",
    email: "botnet@spam.com",
    authProvider: "email",
    tier: "probationary",
    currentRpm: 0,
    rpmLimit: 2,
    todaySpendMicrodollars: 50000,
    activeKeyCount: 0,
    isQuarantined: true,
    lastActiveTimestamp: Date.now() - 86400000,
  },
];

let tenantStore: Map<string, TenantSurveillanceRow> = new Map(
  initialTenants.map((t) => [t.tenantId, { ...t }])
);

let circuitBreakersStore: Record<"gemini" | "groq" | "cerebras" | "deepseek", "NORMAL" | "TRIPPED"> = {
  gemini: "NORMAL",
  groq: "NORMAL",
  cerebras: "NORMAL",
  deepseek: "NORMAL",
};

export function resetAdminStore(): void {
  tenantStore = new Map(initialTenants.map((t) => [t.tenantId, { ...t }]));
  circuitBreakersStore = {
    gemini: "NORMAL",
    groq: "NORMAL",
    cerebras: "NORMAL",
    deepseek: "NORMAL",
  };
}

export function getTenants(): TenantSurveillanceRow[] {
  return Array.from(tenantStore.values());
}

export function updateTenantTier(tenantId: string, newTier: UserTier): TenantSurveillanceRow | undefined {
  const existing = tenantStore.get(tenantId);
  if (!existing) {
    const fresh: TenantSurveillanceRow = {
      tenantId,
      email: `${tenantId}@autogenerated.local`,
      authProvider: "email",
      tier: newTier,
      currentRpm: 0,
      rpmLimit: newTier === "ultra" || newTier === "admin" ? 999999 : 20,
      todaySpendMicrodollars: 0,
      activeKeyCount: 0,
      isQuarantined: false,
      lastActiveTimestamp: Date.now(),
    };
    tenantStore.set(tenantId, fresh);
    return fresh;
  }

  const updated: TenantSurveillanceRow = {
    ...existing,
    tier: newTier,
    rpmLimit: newTier === "ultra" || newTier === "admin" ? 999999 : existing.rpmLimit,
    lastActiveTimestamp: Date.now(),
  };
  tenantStore.set(tenantId, updated);
  return updated;
}

export function setTenantQuarantine(tenantId: string, isQuarantined: boolean): TenantSurveillanceRow | undefined {
  const existing = tenantStore.get(tenantId);
  if (!existing) {
    const fresh: TenantSurveillanceRow = {
      tenantId,
      email: `${tenantId}@autogenerated.local`,
      authProvider: "email",
      tier: "probationary",
      currentRpm: 0,
      rpmLimit: 2,
      todaySpendMicrodollars: 0,
      activeKeyCount: 0,
      isQuarantined,
      lastActiveTimestamp: Date.now(),
    };
    tenantStore.set(tenantId, fresh);
    return fresh;
  }

  const updated: TenantSurveillanceRow = {
    ...existing,
    isQuarantined,
    currentRpm: isQuarantined ? 0 : existing.currentRpm,
    lastActiveTimestamp: Date.now(),
  };
  tenantStore.set(tenantId, updated);
  return updated;
}

export function getPoolHealth(): AdminPoolHealthResponse {
  const anyTripped = Object.values(circuitBreakersStore).some((s) => s === "TRIPPED");

  return {
    status: anyTripped ? "degraded" : "healthy",
    pools: {
      gemini: {
        status: circuitBreakersStore.gemini === "TRIPPED" ? "unhealthy" : "healthy",
        activeKeys: 12,
        circuitBreaker: circuitBreakersStore.gemini === "TRIPPED" ? "open" : "closed",
        failureRate: circuitBreakersStore.gemini === "TRIPPED" ? 0.85 : 0.01,
        totalRequestsToday: 14200,
      },
      groq: {
        status: circuitBreakersStore.groq === "TRIPPED" ? "unhealthy" : "healthy",
        activeKeys: 8,
        circuitBreaker: circuitBreakersStore.groq === "TRIPPED" ? "open" : "closed",
        failureRate: circuitBreakersStore.groq === "TRIPPED" ? 0.9 : 0.0,
        totalRequestsToday: 8900,
      },
      cerebras: {
        status: circuitBreakersStore.cerebras === "TRIPPED" ? "unhealthy" : "healthy",
        activeKeys: 6,
        circuitBreaker: circuitBreakersStore.cerebras === "TRIPPED" ? "open" : "closed",
        failureRate: circuitBreakersStore.cerebras === "TRIPPED" ? 0.95 : 0.0,
        totalRequestsToday: 6200,
      },
      deepseek: {
        status: circuitBreakersStore.deepseek === "TRIPPED" ? "unhealthy" : "healthy",
        activeKeys: 4,
        circuitBreaker: circuitBreakersStore.deepseek === "TRIPPED" ? "open" : "closed",
        failureRate: circuitBreakersStore.deepseek === "TRIPPED" ? 0.8 : 0.02,
        totalRequestsToday: 3100,
      },
    },
    timestamp: Date.now(),
  };
}

export function resetCircuitBreakers(
  provider: "gemini" | "groq" | "cerebras" | "deepseek" | "all" | string
): Record<"gemini" | "groq" | "cerebras" | "deepseek", "NORMAL"> {
  if (provider === "all") {
    circuitBreakersStore = {
      gemini: "NORMAL",
      groq: "NORMAL",
      cerebras: "NORMAL",
      deepseek: "NORMAL",
    };
  } else if (
    provider === "gemini" ||
    provider === "groq" ||
    provider === "cerebras" ||
    provider === "deepseek"
  ) {
    circuitBreakersStore[provider] = "NORMAL";
  }
  return { ...circuitBreakersStore, gemini: "NORMAL", groq: "NORMAL", cerebras: "NORMAL", deepseek: "NORMAL" };
}

export function isValidUserTier(tier: string): tier is UserTier {
  return ["admin", "ultra", "max", "builder", "probationary", "demo", "suspended"].includes(tier);
}
