/**
 * Key Collective v2 — Default Model Catalogue & Pricing Table
 *
 * Invariants (GEMINI.md Constitution):
 * - Credit Units (CU) as first-class billing unit across models.
 * - Fixed-point credit units (bigint / int64) throughout (deprecated, kept until WP-7.3).
 * - Multi-provider benchmark configurations (Google, Groq) callable with free-tier keys.
 */

import type { ModelDef } from "../../types/models";

export const DEFAULT_MODEL_DEFINITIONS: readonly ModelDef[] = [
  {
    id: "gemini-2.0-flash",
    provider: "google",
    logicalAliases: ["smart-fast", "fast-model", "fast"],
    contextWindow: 1_048_576,
    maxOutputTokens: 8192,
    cuBase: 10n,
    cuInPer1k: 1n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 4n,
    supportsTools: true,
    supportsVision: true,
    supportsJsonSchema: true,
    deprecatedAt: "2026-09-01T00:00:00.000Z",
    sunsetAt: "2026-12-31T00:00:00.000Z",
    isActive: true,
    lastSyncedAt: "2026-09-09T00:00:00.000Z",
  },
  {
    id: "gemini-1.5-pro",
    provider: "google",
    logicalAliases: ["smart-model", "reasoning"],
    contextWindow: 2_097_152,
    maxOutputTokens: 8192,
    cuBase: 50n,
    cuInPer1k: 5n,
    cuCachedPer1k: 1n,
    cuOutPer1k: 20n,
    supportsTools: true,
    supportsVision: true,
    supportsJsonSchema: true,
    deprecatedAt: "2026-09-01T00:00:00.000Z",
    sunsetAt: "2026-12-31T00:00:00.000Z",
    isActive: true,
    lastSyncedAt: "2026-09-09T00:00:00.000Z",
  },
  {
    id: "llama-3.3-70b-versatile",
    provider: "groq",
    logicalAliases: ["fast-model", "smart-fast", "open-groq"],
    contextWindow: 128_000,
    maxOutputTokens: 32768,
    cuBase: 10n,
    cuInPer1k: 2n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 4n,
    supportsTools: true,
    supportsVision: false,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-09T00:00:00.000Z",
  },
];

/**
 * Modern Next-Generation Model Definitions.
 * All pricing strictly in int64 credit units (bigint) per 1M tokens.
 */
export const FREE_TIER_MODEL_DEFINITIONS: readonly ModelDef[] = [
  {
    id: "gemini-2.5-flash",
    provider: "google",
    logicalAliases: ["gemini-flash", "google-flash", "flash-2.5", "auto", "smart-fast"],
    contextWindow: 1_048_576,
    maxOutputTokens: 65536,
    cuBase: 10n,
    cuInPer1k: 1n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 4n,
    supportsTools: true,
    supportsVision: true,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-10T00:00:00.000Z",
  },
  {
    id: "gemini-3.5-flash",
    provider: "google",
    logicalAliases: ["gemini-3.5", "flash-3.5"],
    contextWindow: 1_048_576,
    maxOutputTokens: 65536,
    cuBase: 10n,
    cuInPer1k: 1n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 4n,
    supportsTools: true,
    supportsVision: true,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-10T00:00:00.000Z",
  },
  {
    id: "gemini-3.5-flash-lite",
    provider: "google",
    logicalAliases: ["flash-lite", "gemini-lite"],
    contextWindow: 1_048_576,
    maxOutputTokens: 65536,
    cuBase: 5n,
    cuInPer1k: 1n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 2n,
    supportsTools: true,
    supportsVision: true,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-10T00:00:00.000Z",
  },
  {
    id: "gemini-3.1-pro-preview",
    provider: "google",
    logicalAliases: ["gemini-pro", "gemini-3.1-pro", "pro-3.1", "coder-high"],
    contextWindow: 1_048_576,
    maxOutputTokens: 65536,
    cuBase: 50n,
    cuInPer1k: 5n,
    cuCachedPer1k: 1n,
    cuOutPer1k: 20n,
    supportsTools: true,
    supportsVision: true,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-10T00:00:00.000Z",
  },
  {
    id: "gemini-3.8-flash",
    provider: "google",
    logicalAliases: ["smart-fast-next", "gemini-3.8", "flash-3.8"],
    contextWindow: 1_048_576,
    maxOutputTokens: 65536,
    cuBase: 10n,
    cuInPer1k: 1n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 4n,
    supportsTools: true,
    supportsVision: true,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-10T00:00:00.000Z",
  },
  {
    id: "qwen/qwen3.6-27b",
    provider: "groq",
    logicalAliases: ["groq-code", "qwen-27b"],
    contextWindow: 131_072,
    maxOutputTokens: 8192,
    cuBase: 10n,
    cuInPer1k: 2n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 4n,
    supportsTools: true,
    supportsVision: false,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-10T00:00:00.000Z",
  },
  {
    id: "qwen/qwen3.8-27b",
    provider: "groq",
    logicalAliases: ["qwen-3.8", "groq-qwen"],
    contextWindow: 131_072,
    maxOutputTokens: 8192,
    cuBase: 10n,
    cuInPer1k: 2n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 4n,
    supportsTools: true,
    supportsVision: false,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-10T00:00:00.000Z",
  },
  {
    id: "openai/gpt-oss-120b",
    provider: "groq",
    logicalAliases: ["groq-oss", "gpt-oss", "gpt-oss-120b", "coder-high"],
    contextWindow: 131_072,
    maxOutputTokens: 65536,
    cuBase: 10n,
    cuInPer1k: 2n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 4n,
    supportsTools: true,
    supportsVision: false,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-10T00:00:00.000Z",
  },
  {
    id: "openai/gpt-oss-20b",
    provider: "groq",
    logicalAliases: ["gpt-oss-20b", "groq-fast", "open-groq"],
    contextWindow: 131_072,
    maxOutputTokens: 65536,
    cuBase: 5n,
    cuInPer1k: 1n,
    cuCachedPer1k: 0n,
    cuOutPer1k: 1n,
    supportsTools: true,
    supportsVision: false,
    supportsJsonSchema: true,
    deprecatedAt: null,
    sunsetAt: null,
    isActive: true,
    lastSyncedAt: "2026-09-10T00:00:00.000Z",
  },
];

/**
 * All known model definitions combining default paid benchmarks and free-tier models.
 */
export const ALL_MODEL_DEFINITIONS: readonly ModelDef[] = [
  ...DEFAULT_MODEL_DEFINITIONS,
  ...FREE_TIER_MODEL_DEFINITIONS,
];
