/**
 * Key Collective v3.5 — Admin Surveillance Router
 * Conforms to:
 * - PRD v3.5 (Section 2.4: Admin Surveillance Panel)
 * - GEMINI.md Constitution: TypeScript (strict mode, zero `any`), Fixed-Point Microdollars
 * - Data Contracts: TenantSurveillanceRow, AdminActionPayload, ProviderCircuitOverridePayload
 *
 * Endpoints:
 * - GET /admin/api/tenants
 * - POST /admin/api/tenants/:id/role
 * - POST /admin/api/tenants/:id/quarantine
 * - GET /admin/api/pool/health
 * - POST /admin/api/pool/circuit-breaker/reset
 */

import type { UserTier } from "../contracts/v3_types";
import type {
  TenantSurveillanceRow,
  AdminActionPayload,
  ProviderCircuitOverridePayload,
} from "../contracts/v3_5_types";

export type NextFunction = (err?: unknown) => void;

export interface Request {
  method?: string;
  url?: string;
  path?: string;
  params?: Record<string, string>;
  query?: Record<string, string | string[]>;
  headers?: Record<string, string | string[] | undefined> | Headers;
  body?: unknown;
  role?: string;
  user?: {
    id?: string;
    email?: string;
    role?: string;
    tier?: string;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

export interface Response {
  status(code: number): this;
  json(data: unknown): this;
  send(data?: unknown): this;
  setHeader?(name: string, value: string): this;
  statusCode?: number;
  body?: unknown;
  headers?: Record<string, string>;
  [key: string]: unknown;
}

export type RouteHandler = (
  req: Request,
  res: Response,
  next: NextFunction
) => Promise<void> | void;

export interface Route {
  method: string;
  path: string;
  handlers: RouteHandler[];
  paramNames: string[];
  regex: RegExp;
}

export interface RouterInstance {
  (req: Request, res: Response, next?: NextFunction): Promise<void>;
  use(handler: RouteHandler): RouterInstance;
  use(path: string, ...handlers: RouteHandler[]): RouterInstance;
  get(path: string, ...handlers: RouteHandler[]): RouterInstance;
  post(path: string, ...handlers: RouteHandler[]): RouterInstance;
  put(path: string, ...handlers: RouteHandler[]): RouterInstance;
  delete(path: string, ...handlers: RouteHandler[]): RouterInstance;
  handle(req: Request, res: Response, next?: NextFunction): Promise<void>;
  routes: Route[];
  stack: Array<{ path?: string; handler: RouteHandler; method?: string }>;
}

export interface ProviderPoolHealth {
  status: "healthy" | "degraded" | "unhealthy";
  activeKeys: number;
  circuitBreaker: "closed" | "open" | "half-open";
  failureRate: number;
  totalRequestsToday: number;
}

export interface AdminPoolHealthResponse {
  status: "healthy" | "degraded" | "unhealthy";
  pools: Record<"gemini" | "groq" | "cerebras" | "deepseek", ProviderPoolHealth>;
  timestamp: number;
}

// In-memory state storage for surveillance and overrides
const initialTenants: TenantSurveillanceRow[] = [
  {
    tenantId: "tenant_probationary_01",
    email: "dev1@example.com",
    authProvider: "email",
    tier: "probationary",
    currentRpm: 1,
    rpmLimit: 2,
    todaySpendMicrodollars: 15000,
    activeKeyCount: 1,
    isQuarantined: false,
    lastActiveTimestamp: Date.now() - 120000,
  },
  {
    tenantId: "tenant_builder_02",
    email: "builder@example.com",
    authProvider: "github",
    tier: "builder",
    currentRpm: 12,
    rpmLimit: 20,
    todaySpendMicrodollars: 240000,
    activeKeyCount: 4,
    isQuarantined: false,
    lastActiveTimestamp: Date.now() - 30000,
  },
  {
    tenantId: "tenant_quarantined_03",
    email: "botnet@spam.com",
    authProvider: "email",
    tier: "probationary",
    currentRpm: 0,
    rpmLimit: 2,
    todaySpendMicrodollars: 50000,
    activeKeyCount: 0,
    isQuarantined: true,
    lastActiveTimestamp: Date.now() - 86400000,
  },
];

let tenantStore: Map<string, TenantSurveillanceRow> = new Map(
  initialTenants.map((t) => [t.tenantId, { ...t }])
);

let circuitBreakersStore: Record<"gemini" | "groq" | "cerebras" | "deepseek", "NORMAL" | "TRIPPED"> = {
  gemini: "NORMAL",
  groq: "NORMAL",
  cerebras: "NORMAL",
  deepseek: "NORMAL",
};

export function resetAdminStore(): void {
  tenantStore = new Map(initialTenants.map((t) => [t.tenantId, { ...t }]));
  circuitBreakersStore = {
    gemini: "NORMAL",
    groq: "NORMAL",
    cerebras: "NORMAL",
    deepseek: "NORMAL",
  };
}

export function getTenants(): TenantSurveillanceRow[] {
  return Array.from(tenantStore.values());
}

export function updateTenantTier(tenantId: string, newTier: UserTier): TenantSurveillanceRow | undefined {
  const existing = tenantStore.get(tenantId);
  if (!existing) {
    const fresh: TenantSurveillanceRow = {
      tenantId,
      email: `${tenantId}@autogenerated.local`,
      authProvider: "email",
      tier: newTier,
      currentRpm: 0,
      rpmLimit: newTier === "ultra" || newTier === "admin" ? 999999 : 20,
      todaySpendMicrodollars: 0,
      activeKeyCount: 0,
      isQuarantined: false,
      lastActiveTimestamp: Date.now(),
    };
    tenantStore.set(tenantId, fresh);
    return fresh;
  }

  const updated: TenantSurveillanceRow = {
    ...existing,
    tier: newTier,
    rpmLimit: newTier === "ultra" || newTier === "admin" ? 999999 : existing.rpmLimit,
    lastActiveTimestamp: Date.now(),
  };
  tenantStore.set(tenantId, updated);
  return updated;
}

export function setTenantQuarantine(tenantId: string, isQuarantined: boolean): TenantSurveillanceRow | undefined {
  const existing = tenantStore.get(tenantId);
  if (!existing) {
    const fresh: TenantSurveillanceRow = {
      tenantId,
      email: `${tenantId}@autogenerated.local`,
      authProvider: "email",
      tier: "probationary",
      currentRpm: 0,
      rpmLimit: 2,
      todaySpendMicrodollars: 0,
      activeKeyCount: 0,
      isQuarantined,
      lastActiveTimestamp: Date.now(),
    };
    tenantStore.set(tenantId, fresh);
    return fresh;
  }

  const updated: TenantSurveillanceRow = {
    ...existing,
    isQuarantined,
    currentRpm: isQuarantined ? 0 : existing.currentRpm,
    lastActiveTimestamp: Date.now(),
  };
  tenantStore.set(tenantId, updated);
  return updated;
}

export function getPoolHealth(): AdminPoolHealthResponse {
  const anyTripped = Object.values(circuitBreakersStore).some((s) => s === "TRIPPED");

  return {
    status: anyTripped ? "degraded" : "healthy",
    pools: {
      gemini: {
        status: circuitBreakersStore.gemini === "TRIPPED" ? "unhealthy" : "healthy",
        activeKeys: 12,
        circuitBreaker: circuitBreakersStore.gemini === "TRIPPED" ? "open" : "closed",
        failureRate: circuitBreakersStore.gemini === "TRIPPED" ? 0.85 : 0.01,
        totalRequestsToday: 14200,
      },
      groq: {
        status: circuitBreakersStore.groq === "TRIPPED" ? "unhealthy" : "healthy",
        activeKeys: 8,
        circuitBreaker: circuitBreakersStore.groq === "TRIPPED" ? "open" : "closed",
        failureRate: circuitBreakersStore.groq === "TRIPPED" ? 0.9 : 0.0,
        totalRequestsToday: 8900,
      },
      cerebras: {
        status: circuitBreakersStore.cerebras === "TRIPPED" ? "unhealthy" : "healthy",
        activeKeys: 6,
        circuitBreaker: circuitBreakersStore.cerebras === "TRIPPED" ? "open" : "closed",
        failureRate: circuitBreakersStore.cerebras === "TRIPPED" ? 0.95 : 0.0,
        totalRequestsToday: 6200,
      },
      deepseek: {
        status: circuitBreakersStore.deepseek === "TRIPPED" ? "unhealthy" : "healthy",
        activeKeys: 4,
        circuitBreaker: circuitBreakersStore.deepseek === "TRIPPED" ? "open" : "closed",
        failureRate: circuitBreakersStore.deepseek === "TRIPPED" ? 0.8 : 0.02,
        totalRequestsToday: 3100,
      },
    },
    timestamp: Date.now(),
  };
}

export function resetCircuitBreakers(
  provider: "gemini" | "groq" | "cerebras" | "deepseek" | "all" | string
): Record<"gemini" | "groq" | "cerebras" | "deepseek", "NORMAL"> {
  if (provider === "all") {
    circuitBreakersStore = {
      gemini: "NORMAL",
      groq: "NORMAL",
      cerebras: "NORMAL",
      deepseek: "NORMAL",
    };
  } else if (
    provider === "gemini" ||
    provider === "groq" ||
    provider === "cerebras" ||
    provider === "deepseek"
  ) {
    circuitBreakersStore[provider] = "NORMAL";
  }
  return { ...circuitBreakersStore, gemini: "NORMAL", groq: "NORMAL", cerebras: "NORMAL", deepseek: "NORMAL" };
}

function isValidUserTier(tier: string): tier is UserTier {
  return ["admin", "ultra", "max", "builder", "probationary", "demo", "suspended"].includes(tier);
}

function pathToRegex(path: string): { regex: RegExp; paramNames: string[] } {
  const paramNames: string[] = [];
  const regexStr = path
    .replace(/\/:([a-zA-Z0-9_]+)/g, (_match, name) => {
      paramNames.push(name);
      return "/([^/]+)";
    })
    .replace(/\//g, "\/");
  return {
    regex: new RegExp(`^${regexStr}\/?$`),
    paramNames,
  };
}

/**
 * Strict Zero-Knowledge Denial Middleware
 * Returns HTTP 404 Not Found if role is not strictly "admin".
 */
export const verifyAdmin = (req: Request, res: Response, next: NextFunction): void => {
  let role: string | undefined = undefined;

  if (typeof req.role === "string") {
    role = req.role;
  } else if (
    req.user &&
    typeof req.user === "object" &&
    typeof (req.user as Record<string, unknown>).role === "string"
  ) {
    role = (req.user as Record<string, unknown>).role as string;
  } else if (req.headers) {
    if (typeof (req.headers as Headers).get === "function") {
      role = (req.headers as Headers).get("x-user-role") || undefined;
    } else if (typeof req.headers === "object") {
      const headerRole = (req.headers as Record<string, string | string[] | undefined>)["x-user-role"];
      if (typeof headerRole === "string") {
        role = headerRole;
      }
    }
  }

  // Strict role checking (role === "admin")
  if (role === "admin") {
    next();
    return;
  }

  // Zero-knowledge denial (returns 404 Not Found if role is not admin)
  res.status(404).json({
    error: "Not Found",
  });
};

/**
 * Router Factory function creating a lightweight, composable HTTP router.
 */
export function Router(): RouterInstance {
  const routes: Route[] = [];
  const globalMiddlewares: RouteHandler[] = [];
  const stack: Array<{ path?: string; handler: RouteHandler; method?: string }> = [];

  const handle = async (
    req: Request,
    res: Response,
    finalNext?: NextFunction
  ): Promise<void> => {
    req.params = req.params ?? {};
    req.query = req.query ?? {};

    const rawUrl = req.url || req.path || "/";
    const [pathname, queryString] = rawUrl.split("?");

    if (queryString && Object.keys(req.query).length === 0) {
      const searchParams = new URLSearchParams(queryString);
      searchParams.forEach((val, key) => {
        if (req.query) {
          req.query[key] = val;
        }
      });
    }

    const method = (req.method || "GET").toUpperCase();

    // Find matching route
    for (const route of routes) {
      if (route.method !== method && route.method !== "ALL") {
        continue;
      }

      const match = pathname.match(route.regex);
      if (match) {
        for (let i = 0; i < route.paramNames.length; i++) {
          req.params[route.paramNames[i]] = decodeURIComponent(match[i + 1]);
        }

        const pipeline = [...globalMiddlewares, ...route.handlers];
        let index = 0;

        const next: NextFunction = (err?: unknown) => {
          if (err) {
            if (finalNext) {
              finalNext(err);
              return;
            }
            res.status(500).json({ error: String(err) });
            return;
          }

          if (index < pipeline.length) {
            const handler = pipeline[index++];
            try {
              const result = handler(req, res, next);
              if (result && typeof (result as Promise<void>).then === "function") {
                (result as Promise<void>).catch((asyncErr) => next(asyncErr));
              }
            } catch (syncErr) {
              next(syncErr);
            }
          } else if (finalNext) {
            finalNext();
          }
        };

        next();
        return;
      }
    }

    if (finalNext) {
      finalNext();
    } else {
      res.status(404).json({ error: "Not Found" });
    }
  };

  const routerFn = ((req: Request, res: Response, next?: NextFunction) => {
    return handle(req, res, next);
  }) as RouterInstance;

  routerFn.routes = routes;
  routerFn.stack = stack;
  routerFn.handle = handle;

  routerFn.use = (
    pathOrHandler: string | RouteHandler,
    ...handlers: RouteHandler[]
  ): RouterInstance => {
    if (typeof pathOrHandler === "function") {
      globalMiddlewares.push(pathOrHandler);
      stack.push({ handler: pathOrHandler });
      for (const h of handlers) {
        globalMiddlewares.push(h);
        stack.push({ handler: h });
      }
    } else if (typeof pathOrHandler === "string") {
      for (const h of handlers) {
        const { regex, paramNames } = pathToRegex(
          pathOrHandler.endsWith("*") ? pathOrHandler.slice(0, -1) + ".*" : pathOrHandler
        );
        routes.push({
          method: "ALL",
          path: pathOrHandler,
          handlers: [h],
          paramNames,
          regex,
        });
        stack.push({ path: pathOrHandler, handler: h });
      }
    }
    return routerFn;
  };

  routerFn.get = (path: string, ...handlers: RouteHandler[]): RouterInstance => {
    const { regex, paramNames } = pathToRegex(path);
    routes.push({
      method: "GET",
      path,
      handlers,
      paramNames,
      regex,
    });
    stack.push({ path, handler: handlers[handlers.length - 1], method: "GET" });
    return routerFn;
  };

  routerFn.post = (path: string, ...handlers: RouteHandler[]): RouterInstance => {
    const { regex, paramNames } = pathToRegex(path);
    routes.push({
      method: "POST",
      path,
      handlers,
      paramNames,
      regex,
    });
    stack.push({ path, handler: handlers[handlers.length - 1], method: "POST" });
    return routerFn;
  };

  routerFn.put = (path: string, ...handlers: RouteHandler[]): RouterInstance => {
    const { regex, paramNames } = pathToRegex(path);
    routes.push({
      method: "PUT",
      path,
      handlers,
      paramNames,
      regex,
    });
    stack.push({ path, handler: handlers[handlers.length - 1], method: "PUT" });
    return routerFn;
  };

  routerFn.delete = (path: string, ...handlers: RouteHandler[]): RouterInstance => {
    const { regex, paramNames } = pathToRegex(path);
    routes.push({
      method: "DELETE",
      path,
      handlers,
      paramNames,
      regex,
    });
    stack.push({ path, handler: handlers[handlers.length - 1], method: "DELETE" });
    return routerFn;
  };

  return routerFn;
}

// ---------------------------------------------------------------------------
// Route Handlers
// ---------------------------------------------------------------------------

const getTenantsHandler: RouteHandler = (_req, res) => {
  const tenants = getTenants();
  res.status(200).json({
    success: true,
    tenants,
    total: tenants.length,
  });
};

const updateTenantRoleHandler: RouteHandler = (req, res) => {
  const tenantId = req.params?.id;
  if (!tenantId) {
    res.status(400).json({ error: "Missing tenant id parameter" });
    return;
  }

  const body = (req.body ?? {}) as Record<string, unknown>;
  const rawTier = body.tier ?? body.newTier ?? body.role;

  if (typeof rawTier !== "string" || !isValidUserTier(rawTier)) {
    res.status(400).json({
      error: "Invalid or missing tier/role parameter",
      validTiers: ["admin", "ultra", "max", "builder", "probationary", "demo", "suspended"],
    });
    return;
  }

  const updated = updateTenantTier(tenantId, rawTier as UserTier);
  res.status(200).json({
    success: true,
    tenantId,
    tier: rawTier,
    updated: !!updated,
    reason: typeof body.reason === "string" ? body.reason : "Admin role mutation",
  });
};

const quarantineTenantHandler: RouteHandler = (req, res) => {
  const tenantId = req.params?.id;
  if (!tenantId) {
    res.status(400).json({ error: "Missing tenant id parameter" });
    return;
  }

  const body = (req.body ?? {}) as Record<string, unknown>;
  const isQuarantined =
    typeof body.isQuarantined === "boolean"
      ? body.isQuarantined
      : typeof body.quarantined === "boolean"
      ? body.quarantined
      : true;

  const reason = typeof body.reason === "string" ? body.reason : "Admin quarantine action";
  const updated = setTenantQuarantine(tenantId, isQuarantined);

  res.status(200).json({
    success: true,
    tenantId,
    isQuarantined,
    updated: !!updated,
    reason,
  });
};

const getPoolHealthHandler: RouteHandler = (_req, res) => {
  const health = getPoolHealth();
  res.status(200).json(health);
};

const resetCircuitBreakerHandler: RouteHandler = (req, res) => {
  const body = (req.body ?? {}) as Record<string, unknown>;
  const provider = typeof body.provider === "string" ? body.provider.toLowerCase() : "all";

  const validProviders = ["gemini", "groq", "cerebras", "deepseek", "all"];
  if (!validProviders.includes(provider)) {
    res.status(400).json({
      error: `Invalid provider: '${provider}'. Valid options: ${validProviders.join(", ")}`,
    });
    return;
  }

  const resetResult = resetCircuitBreakers(provider);
  res.status(200).json({
    success: true,
    provider,
    reset: true,
    state: "NORMAL",
    circuitBreakers: resetResult,
    reason: typeof body.reason === "string" ? body.reason : "Admin circuit breaker reset",
  });
};

// ---------------------------------------------------------------------------
// Singleton adminRouter Instance & Route Registration
// ---------------------------------------------------------------------------

export const adminRouter = Router();

// Apply strict zero-knowledge denial middleware
adminRouter.use(verifyAdmin);

// 1. GET /admin/api/tenants & GET /tenants
adminRouter.get("/admin/api/tenants", getTenantsHandler);
adminRouter.get("/tenants", getTenantsHandler);

// 2. POST /admin/api/tenants/:id/role & POST /tenants/:id/role
adminRouter.post("/admin/api/tenants/:id/role", updateTenantRoleHandler);
adminRouter.post("/tenants/:id/role", updateTenantRoleHandler);

// 3. POST /admin/api/tenants/:id/quarantine & POST /tenants/:id/quarantine
adminRouter.post("/admin/api/tenants/:id/quarantine", quarantineTenantHandler);
adminRouter.post("/tenants/:id/quarantine", quarantineTenantHandler);

// 4. GET /admin/api/pool/health & GET /pool/health
adminRouter.get("/admin/api/pool/health", getPoolHealthHandler);
adminRouter.get("/pool/health", getPoolHealthHandler);

// 5. POST /admin/api/pool/circuit-breaker/reset & POST /pool/circuit-breaker/reset
adminRouter.post("/admin/api/pool/circuit-breaker/reset", resetCircuitBreakerHandler);
adminRouter.post("/pool/circuit-breaker/reset", resetCircuitBreakerHandler);

// ---------------------------------------------------------------------------
// Mock Helpers for Testing
// ---------------------------------------------------------------------------

export function createMockRequest(options: {
  method?: string;
  url?: string;
  role?: string;
  user?: { id?: string; email?: string; role?: string; tier?: string };
  headers?: Record<string, string>;
  body?: unknown;
  params?: Record<string, string>;
  query?: Record<string, string>;
} = {}): Request {
  return {
    method: options.method || "GET",
    url: options.url || "/",
    path: options.url || "/",
    role: options.role,
    user: options.user,
    headers: options.headers || {},
    body: options.body,
    params: options.params || {},
    query: options.query || {},
  };
}

export function createMockResponse(): Response {
  const res: Response = {
    statusCode: 200,
    headers: {},
    body: undefined,
    status(code: number) {
      this.statusCode = code;
      return this;
    },
    json(data: unknown) {
      this.body = data;
      return this;
    },
    send(data?: unknown) {
      this.body = data;
      return this;
    },
    setHeader(name: string, value: string) {
      if (!this.headers) this.headers = {};
      this.headers[name] = value;
      return this;
    },
  };
  return res;
}
