/**
 * Key Collective v4.0 — Data Contracts (TypeScript / Zod v3)
 * All schemas correspond to D1 table rows and DO in-memory state.
 * Generated by: Inception Board Ground Worker
 * Date: 2026-09-14
 */

import { z } from "zod";

// ─────────────────────────────────────────────────────────────────────────────
// CONSENT ATTESTATION
// Records the legal clickwrap consent at registration (C1/C2/C3) and key submission (K1/K2).
// Stored in D1 `consent_attestations` table (append-only).
// ─────────────────────────────────────────────────────────────────────────────

export const ConsentAttestationSchema = z.object({
  /** Unique attestation record ID */
  id: z.string().uuid(),
  /** Tenant identifier this attestation belongs to */
  tenant_id: z.string().min(1),
  /** Consent type */
  consent_type: z.enum(["C1", "C2", "C3", "K1", "K2"]),
  /** Version hash of the consent document signed */
  consent_version: z.string().min(1),
  /** Unix timestamp of attestation */
  attested_at: z.number().int().positive(),
});

export type ConsentAttestation = z.infer<typeof ConsentAttestationSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// API KEY
// Represents a provider API key contributed to the system.
// Stored in D1 `api_keys` table (encrypted at rest via HKDF + AES-256-GCM).
// ─────────────────────────────────────────────────────────────────────────────

export const ApiKeySchema = z.object({
  /** Unique identifier for this key record */
  id: z.string().uuid(),
  /** Owning tenant's identifier */
  tenant_id: z.string().min(1),
  /** Human-readable label for the key */
  label: z.string().min(1).max(100),
  /** LLM provider */
  provider: z.enum(["gemini", "groq", "sambanova", "cerebras", "openai", "anthropic"]),
  /** Pool allocation mode */
  pool_type: z.enum(["PRIVATE", "COMMUNITY"]),
  /** Current routing status within the community pool lifecycle */
  community_routing_status: z.enum(["OBSERVATION", "ACTIVE", "QUARANTINED", "REVOKED"]),
  /** Project hash registry state for anti-sybil tracking */
  project_hash_state: z.enum(["ACTIVE", "ROTATING", "TOMBSTONED"]),
  /**
   * Vesting tier based on contribution longevity.
   * Tier 1 (Bronze, <30 days): 1.5× multiplier
   * Tier 2 (Silver, 30-90 days): 3.0× multiplier
   * Tier 3 (Gold, >90 days): 4.5× multiplier
   */
  vesting_tier: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  /** Unix timestamp until which the key remains in OBSERVATION state (null = not observing) */
  observation_until: z.number().int().positive().nullable(),
  /**
   * Unix timestamp until which the 30-minute rotation grace period is active.
   * During this window, submitting a replacement key preserves vesting_tier.
   */
  rotating_until: z.number().int().positive().nullable(),
  /** SHA-256 hash of the GCP project extracted via Forced-Error Probe */
  gcp_project_hash: z.string().length(64).nullable(),
  /** AES-256-GCM ciphertext of the raw API key (HKDF-derived per-tenant key) */
  encrypted_key_material: z.string().min(1),
  /** 12-byte Base64-encoded nonce used for AES-256-GCM encryption */
  nonce: z.string().min(16),
  /** Unix timestamp of key creation */
  created_at: z.number().int().positive(),
  /** Custom RPM limit (null = use provider default) */
  rpm_limit: z.number().int().positive().nullable(),
  /** Custom RPD limit (null = use provider default) */
  rpd_limit: z.number().int().positive().nullable(),
});

export type ApiKey = z.infer<typeof ApiKeySchema>;

// ─────────────────────────────────────────────────────────────────────────────
// COMMUNITY DEBT LEDGER
// Tracks a tenant's Compute Unit (CU) debt and decay.
// Stored in D1 `contributor_standing` table.
// ─────────────────────────────────────────────────────────────────────────────

export const CommunityDebtLedgerSchema = z.object({
  /** Tenant identifier */
  tenant_id: z.string().min(1),
  /**
   * Current community debt in micro-CUs (net, after CCC offset).
   * 1 CU = 1,000,000 micro-CUs. MUST use integer arithmetic only.
   *
   * Contribution Capacity Credit model (ADR-005):
   *   debt_delta = max(0, CU_consumed_from_pool - daily_free_draw_micro_cu)
   * Debt only accrues when consumption EXCEEDS the free draw entitlement.
   * A contributor who is the sole or primary pool consumer will NOT be
   * penalized as long as consumption <= contributed capacity x multiplier.
   */
  community_debt_micro_cu: z.number().int().nonnegative(),
  /**
   * Daily free-draw entitlement in micro-CUs (ADR-005 CCC model):
   *   daily_free_draw = sum over active community keys of:
   *     key.nominal_daily_cu x health_score(key) x vesting_multiplier
   * Recalculated on key add/remove/health-change. Resets at UTC midnight.
   */
  daily_free_draw_micro_cu: z.number().int().nonnegative(),
  /**
   * Running total of micro-CUs drawn from the community pool today.
   * Compared against daily_free_draw_micro_cu to compute debt delta.
   * Resets at UTC midnight alongside decay.
   */
  daily_consumed_from_pool_micro_cu: z.number().int().nonnegative(),
  /** ISO date string (YYYY-MM-DD) of the last 30% decay applied */
  last_decay_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  /** Current jail level (based on net debt vs. free draw entitlement) */
  jail_status: z.enum(["PRISTINE", "SOFT_WARNING", "HARD_JAIL"]),
  /**
   * Consecutive days tenant maintained 0 net debt (consumed <= free draw).
   * 7+ days = Trusted Contributor badge.
   */
  trusted_contributor_streak_days: z.number().int().nonnegative(),
  /** Unix timestamp of last update */
  updated_at: z.number().int().positive(),
});

export type CommunityDebtLedger = z.infer<typeof CommunityDebtLedgerSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// CONTRIBUTOR STANDING
// Computed standing and burst multiplier for a tenant. Derived from debt ledger.
// Maintained in KeyPoolDO in-memory; synced to D1 asynchronously.
// ─────────────────────────────────────────────────────────────────────────────

export const ContributorStandingSchema = z.object({
  /** Tenant identifier */
  tenant_id: z.string().min(1),
  /**
   * Current computed burst multiplier.
   * PRISTINE + TIER_3: 4.5 | PRISTINE + TIER_2: 3.0 | PRISTINE + TIER_1: 1.5
   * SOFT_WARNING: max 1.5 | HARD_JAIL: exactly 1.0 (own keys only)
   */
  current_multiplier: z.number().min(1.0).max(4.5),
  /** Whether the tenant has earned the Trusted Contributor badge (7-day Pristine streak) */
  is_trusted_contributor: z.boolean(),
  /** Current debt-based jail status */
  jail_status: z.enum(["PRISTINE", "SOFT_WARNING", "HARD_JAIL"]),
  /**
   * CCC model thresholds (ADR-005). Thresholds apply to NET debt:
   *   net_debt = max(0, daily_consumed_from_pool - daily_free_draw_micro_cu)
   * SOFT_WARNING: net_debt > 0.5 x daily_free_draw_micro_cu
   * HARD_JAIL:    net_debt > 1.0 x daily_free_draw_micro_cu
   *
   * A contributor who is the sole pool consumer will have net_debt = 0
   * as long as consumption <= contributed capacity x vesting multiplier.
   */
  debt_threshold_ratio: z.number().min(0),

export type ContributorStanding = z.infer<typeof ContributorStandingSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// ROUTING DECISION
// Describes how a single inference request was routed. Written to Analytics Engine.
// ─────────────────────────────────────────────────────────────────────────────

export const RoutingDecisionSchema = z.object({
  /** Type of routing path taken */
  route_type: z.enum([
    "SELF_KEY",           // Tenant's own healthy key served the request
    "COMMUNITY_POOL",     // Communal pool key served the request
    "QUOTA_JAIL_REJECT",  // Request blocked due to Hard Jail status
    "DEMO_POOL",          // Unauthenticated demo mode via DemoDO
    "PROVIDER_NOT_CONTRIBUTED", // Eye-for-an-Eye: requested provider not contributed
    "POOL_EMPTY",         // Community pool has no active keys for provider
  ]),
  /** Key ID used to serve the request (undefined if rejected) */
  selected_key_id: z.string().uuid().optional(),
  /** Provider of the selected key */
  selected_provider: z.enum(["gemini", "groq", "sambanova", "cerebras", "openai", "anthropic"]).optional(),
  /**
   * Compute Units charged to tenant's debt ledger.
   * 0 for SELF_KEY; >0 for COMMUNITY_POOL; 0 for rejections.
   */
  cu_cost_micro: z.number().int().nonnegative(),
  /** Routing overhead in milliseconds (target: <5ms P95) */
  routing_overhead_ms: z.number().nonnegative(),
  /** Rejection reason if route_type is a rejection */
  reject_reason: z.string().optional(),
});

export type RoutingDecision = z.infer<typeof RoutingDecisionSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// TAKEDOWN REPORT
// Validates incoming POST /report abuse endpoint requests.
// Never stored in D1 — only the SHA-256 hash is checked against in-memory set.
// ─────────────────────────────────────────────────────────────────────────────

export const TakedownReportSchema = z.object({
  /**
   * The leaked API key in plaintext.
   * Will be SHA-256 hashed and compared against PoolCoordinatorDO's active key hash set.
   * NEVER stored. Used only for the in-memory constant-time hash lookup.
   */
  leaked_key: z.string().min(10).max(512),
  /** Cloudflare Turnstile token for abuse rate protection (5 req/IP/hr) */
  turnstile_token: z.string().min(1),
  /**
   * Optional URL where the leaked key was found (for audit log, hashed).
   * Helps identify leak sources for policy action.
   */
  source_url: z.string().url().optional(),
});

export type TakedownReport = z.infer<typeof TakedownReportSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// POOL METRICS
// Global communal pool health state. Maintained by PoolCoordinatorDO in-memory.
// ─────────────────────────────────────────────────────────────────────────────

export const PoolMetricsSchema = z.object({
  /** Total active community keys across all providers */
  total_active_keys: z.number().int().nonnegative(),
  /** Breakdown of active keys per provider */
  keys_by_provider: z.record(z.string(), z.number().int().nonnegative()),
  /**
   * Pool health ratio: (healthy keys) / (total community keys)
   * A ratio below 0.5 triggers admin alert.
   */
  pool_health_ratio: z.number().min(0).max(1),
  /** Count of keys currently in 24h observation (not yet serving communal traffic) */
  keys_in_observation: z.number().int().nonnegative(),
  /** Count of quarantined keys (failing health checks) */
  keys_quarantined: z.number().int().nonnegative(),
  /**
   * Current aggregate $W_{\text{provider}}$ quality weights.
   * Higher weight = better success rate in last 1h window.
   */
  provider_quality_weights: z.record(z.string(), z.number().min(0).max(1)),
  /** Unix timestamp of this metrics snapshot */
  snapshot_time: z.number().int().positive(),
  /** Active tenants in the last 5 minutes (for Anomalous Spiker Brake denominator) */
  active_tenants_5min: z.number().int().nonnegative(),
});

export type PoolMetrics = z.infer<typeof PoolMetricsSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// PROJECT HASH REGISTRY
// Tracks GCP project hashes for anti-sybil duplicate detection.
// Stored in D1 `project_hash_registry` table.
// ─────────────────────────────────────────────────────────────────────────────

export const ProjectHashRegistrySchema = z.object({
  /** SHA-256 hash of the GCP project number extracted via Forced-Error Probe */
  gcp_project_hash: z.string().length(64),
  /** Current state of this project hash in the registry */
  state: z.enum(["ACTIVE", "ROTATING", "TOMBSTONED"]),
  /**
   * Unix timestamp when the hash entered TOMBSTONED state.
   * Null until tombstoned. 14-day ban expires at tombstoned_at + (14 * 86400).
   */
  tombstoned_at: z.number().int().positive().nullable(),
  /** Tenant ID that registered this project hash */
  tenant_id: z.string().min(1),
  /** Unix timestamp of first registration */
  created_at: z.number().int().positive(),
});

export type ProjectHashRegistry = z.infer<typeof ProjectHashRegistrySchema>;
